version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: startup_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build: .
    container_name: php_apache
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@startup.com
      PGADMIN_DEFAULT_PASSWORD: sua_senha_pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
