version: '3.8'

services:
  postgres:
    build: 
      context: ./postgres 
      dockerfile: Dockerfile
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: startup_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: startup_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin-data:
