version: '3.8'

services:
  postgres:
    build: 
      context: ./postgres # Caminho até a pasta onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: startup_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: startup_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

volumes:
  pgdata:
