FROM postgres:latest

# Variáveis de ambiente pra inicialização do banco
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=startup_db

# Copia o script de inicialização (se tiver)
WORKDIR /var/lib/postgresql/data


